{% set name = "useDAVE" %}
{% set version = "2.0.0" %}                         
package:
  name: dave
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea877a494fa36de4140803bda2c089debbece0dd2e2efa00e262c498b0018b96

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - pyscaffold
  run:
    - python >=3.9
    - vtk >=9.0.0
    - ipython
    - pyside6
    - numpy
    - scipy
    - matplotlib-base
    - prettytable
    - netCDF4
    - vedo
    - xarray
    - pyyaml
    - rapidfuzz
    - mafredo >=0.1

test:
  # Minimal tests:
  imports:
    - numpy

about:
  home: https://github.com/RubendeBruin/DAVE
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Difficult Analysis Very Easy
  # The remaining entries in this section are optional, but recommended.
  description: |
    DAVE is a python package for bookkeeping and visualization of floating, suspended and/or mechanical systems. It provides a general coordinates based geometry module and a graphical user interface.
    Assets are the main building blocks of a model. Assets are digital versions of physical objects and contain all information required to use the item in engineering. Assets can be imported into a scene (a model). In a scene assets can be connected to eachother and external influences like wind and water can be added.
    Various solvers can then be used to investigate how a model behaves. Static equilibrium can be calculated via the EquilibriumCore plugin. This core supports buoyancy based on linear hydrostatics or an imported shape. The static equilibrium conditions allows for stability checks, static load distributions in lifting ropes, internal loads, static clearance checks and much more.
    Exporting to other software packages is possible. By default an export routine to Blender (3d visualization and animation) is included. The design of DAVE is such that export to software such as dynamic simulation packages, simulation software or game engines can easily be added.
  doc_url: https://open-ocean.org/DAVE/
  dev_url: https://github.com/RubendeBruin/DAVE

extra:
  recipe-maintainers:
    - RubendeBruin
